/** @file Execute real PostgreSQL store methods against a recording driver double. Real constraints are tested separately on Neon. */
import test from 'node:test';
import assert from 'node:assert/strict';
import {createDraftJobStore} from '../draft-job-store.mjs';

/** Predetermine driver results, retaining exact parameterized statements and transaction ordering. */
function fixture(results) {
  const calls=[],sealed=[];let releases=0;
  const client={async query(text,values){calls.push({text,values});if(/^(BEGIN|COMMIT|ROLLBACK|SET LOCAL)/.test(text))return{rows:[]};const next=results.shift();if(next instanceof Error)throw next;return{rows:next??[]};},release(){releases++;}};
  const store=createDraftJobStore({pool:{connect:async()=>client},seal:value=>{sealed.push(value);return'OPAQUE_CIPHERTEXT';},open:value=>JSON.parse(value),draftLimit:20});
  return{store,calls,sealed,get releases(){return releases;}};
}

test('create encrypts request content and binds idempotency to the owner inside a short transaction',async()=>{const f=fixture([[],[],[{active:0,recent:0}],[{id:'newjob'}]]);await f.store.create('owner','same-key-001','a'.repeat(64),{feature:'PRIVATE_CODE'});const insert=f.calls.find(c=>c.text.startsWith('INSERT INTO public.repot_draft_job'));assert.equal(insert.values[4],'OPAQUE_CIPHERTEXT');assert.equal(insert.values[1],'owner');assert.ok(!JSON.stringify(f.calls).includes('PRIVATE_CODE'));assert.equal(f.sealed[0].request.feature,'PRIVATE_CODE');assert.equal(f.calls.at(-1).text,'COMMIT');assert.equal(f.releases,1);});
test('an existing request key returns prior job before another insert',async()=>{const f=fixture([[],[{id:'existing',request_hash:'same'}]]);assert.equal((await f.store.create('owner','same-key-001','same',{})).id,'existing');assert.ok(!f.calls.some(c=>c.text.startsWith('INSERT')));});
test('key conflict rolls back and always releases the connection',async()=>{const f=fixture([[],[{request_hash:'other'}]]);await assert.rejects(f.store.create('owner','same-key-001','requested',{}),e=>e.code==='request_key_conflict');assert.equal(f.calls.at(-1).text,'ROLLBACK');assert.equal(f.releases,1);});
test('active-job cap rejects before insertion',async()=>{const f=fixture([[],[],[{active:3,recent:3}]]);await assert.rejects(f.store.create('owner','same-key-001','requested',{}),e=>e.code==='too_many_jobs');assert.ok(!f.calls.some(c=>c.text.startsWith('INSERT')));});
test('queries for job ownership bind BOTH job and authenticated user',async()=>{const f=fixture([[{id:'job'}]]);await f.store.get('owner','job');const select=f.calls.find(c=>c.text.startsWith('SELECT'));assert.match(select.text,/id=\$1 AND user_id=\$2/);assert.deepEqual(select.values,['job','owner']);});
test('quota failure cannot mark submission intent or consume another allowance',async()=>{const claimed={id:'job',user_id:'owner',lease_token:'lease',state:'prepared',cancel_requested:false};const f=fixture([[claimed],[],[{drafts:20}]]);await assert.rejects(f.store.beginSubmission(claimed),e=>e.code==='draft_limit');assert.ok(!f.calls.some(c=>c.text.startsWith('UPDATE')));assert.equal(f.calls.at(-1).text,'ROLLBACK');});
test('lease mismatch prevents any state update',async()=>{const f=fixture([[{lease_token:'different'}]]);await assert.rejects(f.store.prepared({user_id:'owner',id:'job',lease_token:'old'},{}));assert.ok(!f.calls.some(c=>c.text.startsWith('UPDATE')));});
test('review insertion and completed job reference share one commit and encrypted review bytes',async()=>{const claimed={id:'job',user_id:'owner',lease_token:'lease',state:'running'};const f=fixture([[claimed],[],[{state:'completed'}]]);await f.store.complete(claimed,{source:{meta:{name:'a/source'}},destination:{meta:{name:'b/dest'},snapshot:{revision:'a'.repeat(40)}}},{patch:'PRIVATE_PATCH'});const writes=f.calls.filter(c=>/^(INSERT|UPDATE)/.test(c.text));assert.equal(writes.length,2);assert.match(writes[0].text,/INSERT INTO public.repot_review/);assert.equal(writes[0].values[5],'OPAQUE_CIPHERTEXT');assert.match(writes[1].text,/state='completed'/);assert.equal(writes[0].values[0],writes[1].values[2]);assert.ok(!JSON.stringify(f.calls).includes('PRIVATE_PATCH'));assert.equal(f.calls.at(-1).text,'COMMIT');});
test('a cancellation observed inside finalization writes no review',async()=>{const claimed={id:'job',user_id:'owner',lease_token:'lease',state:'running',cancel_requested:true};const f=fixture([[claimed]]);await f.store.complete(claimed,{},{});assert.ok(!f.calls.some(c=>/^(INSERT|UPDATE)/.test(c.text)));});
