/** @file Scoped-job, model-context and pre-generation budgeting regressions with simulated service I/O. */
import test from 'node:test';
import assert from 'node:assert/strict';
import {createHash} from 'node:crypto';
import {draftRequest,createDraftJobs} from '../draft-jobs.mjs';
import {repairFixture,request,source,destination,context} from './repair-fixture.mjs';
import {loadTestAI} from './repair-load-ai.mjs';
/** Stable content identity uses the same JSON construction as the pre-selector implementation. */
const digest=value=>createHash('sha256').update(JSON.stringify(value)).digest('hex');
test('unscoped request hashes retain their existing recovery identity',()=>{const normalized=draftRequest(request);const expected={maxRepairAttempts:2,sourceRepo:request.sourceRepo,destinationRepo:request.destinationRepo,feature:request.feature,allowAI:true,allowBackgroundProcessing:true};assert.equal(normalized.requestHash,digest(expected));delete expected.maxRepairAttempts;assert.equal(normalized.legacyRequestHash,digest(expected));});
test('selected source/destination paths are canonical, hashed and persisted with the same request',()=>{const a=draftRequest({...request,sourcePaths:['b.dart','a.dart'],destinationPaths:['lib/home.dart']}),b=draftRequest({...request,sourcePaths:['a.dart','b.dart'],destinationPaths:['lib/home.dart']});assert.deepEqual(a.request.sourcePaths,['a.dart','b.dart']);assert.equal(a.requestHash,b.requestHash);assert.notEqual(a.requestHash,draftRequest(request).requestHash);});
test('unsafe or empty scopes fail before creating a job or calling the provider',async()=>{const f=await repairFixture([]);for(const sourcePaths of [['../x.dart'],[],['.env']])await assert.rejects(f.service().start('alice',{...request,sourcePaths}),e=>e.code==='invalid_request');assert.equal(f.jobs.size,0);assert.equal(f.requests.length,0);});
test('a missing-context plan terminates explicitly before charging or model submission',async()=>{const f=await repairFixture([]);const service=createDraftJobs({store:f.store,provider:f.provider,prepare:async()=>({context:{integrationPlan:{contextCoverage:{complete:false}}}}),buildRequest:()=>assert.fail('must not build'),reviewResponse:()=>assert.fail('must not review')});const started=await service.start('alice',request);const result=await service.status('alice',started.jobId);assert.equal(result.status,'failed');assert.equal(result.error.code,'context_budget_exceeded');assert.equal(f.charges,0);assert.equal(f.requests.length,0);});
test('model request receives the plan as data and still disallows execution and test weakening',async()=>{const ai=await loadTestAI();const integrationPlan={version:1,platformChecks:['permissions and entitlements'],verification:[{program:'flutter',args:['test'],status:'not_run'}],contextCoverage:{complete:true}};const p=ai.buildProposalRequest({source,destination,context:{...context,integrationPlan}});assert.deepEqual(JSON.parse(p.input).integrationPlan,integrationPlan);assert.match(p.instructions,/do not claim to have run/);assert.match(p.instructions,/never change source tests/);assert.equal(p.model,'gpt-6.1-sol');assert.equal(p.max_output_tokens,12000);});
test('model builder rejects context gaps before any billable provider request',async()=>{const ai=await loadTestAI();assert.throws(()=>ai.buildProposalRequest({source,destination,context:{...context,integrationPlan:{contextCoverage:{complete:false}}}}),e=>e.diagnostic.code==='proposal_context_insufficient');});
test('repair attempts retain the original selected paths in the durable request',async()=>{const f=await repairFixture([]);const a=await f.service().start('alice',{...request,sourcePaths:['src/json.js'],destinationPaths:['src/app.js']});const row=f.jobs.get(a.jobId);assert.deepEqual(JSON.parse(row.payload).request.sourcePaths,['src/json.js']);const again=await f.service().start('alice',{...request,sourcePaths:['src/json.js'],destinationPaths:['src/app.js']});assert.equal(again.jobId,a.jobId);await assert.rejects(f.service().start('alice',{...request,sourcePaths:['other.js']}),e=>e.code==='request_key_conflict');});
