/** @file Real lexical graph/planner tests on synthetic multi-language projects; no provider or build execution. */
import test from 'node:test';
import assert from 'node:assert/strict';
import {sourceTokens,dartDirectives,sourceGraph,dependencyClosure} from '../lib/source-graph.mjs';
import {planFeature,finalizePlan,compactPlan,normalizeSelection,selectContext} from '../lib/feature-plan.mjs';
/** A test repository with exactly known files and optional unread inventory paths. */
const repo=entries=>({files:Object.entries(entries).map(([path,content])=>({path,content})),inventory:Object.keys(entries)});
/** A tiny Flutter package with a transitive feature and a related unit test. */
function flutter(name='source_app') {return repo({'pubspec.yaml':`name: ${name}\ndependencies:\n  flutter:\n    sdk: flutter\ndev_dependencies:\n  flutter_test:\n    sdk: flutter\n`,'lib/cart.dart':"import 'price.dart';\nint total() => price;",'lib/price.dart':'const price=4;','test/cart_test.dart':`import 'package:${name}/cart.dart';\nimport 'package:flutter_test/flutter_test.dart';\nvoid main(){test('cart',(){expect(total(),4);});}`});}
test('Dart directives preserve exact quoted spans and ignore comments, strings and function bodies',()=>{const text=`// import 'secret.dart';\n/* nested /* import 'hidden.dart'; */ */\nimport 'a.dart' as a;\nexport "b.dart" show B;\nfinal fake="import 'fake.dart';";\nvoid main(){ print("import 'inner.dart';"); }`;const d=dartDirectives({content:text});assert.deepEqual(d.directives.map(r=>r.specifier),['a.dart','b.dart']);assert.ok(d.directives.every(r=>text.slice(r.start,r.end)===r.specifier));assert.deepEqual(d.issues,[]);});
test('Dart conditional imports retain both platform dependencies',()=>{const r=repo({'pubspec.yaml':'name: app\n','lib/a.dart':"import 'stub.dart' if (dart.library.io) 'io.dart';",'lib/stub.dart':'','lib/io.dart':''});const g=sourceGraph(r);assert.deepEqual(dependencyClosure(g,['lib/a.dart']),['lib/a.dart','lib/io.dart','lib/stub.dart']);assert.ok(g.issues.some(i=>i.code==='conditional_platform_directive'));});
test('Dart self-package imports resolve to the nearest monorepo package',()=>{const g=sourceGraph(repo({'a/pubspec.yaml':'name: aa\n','a/lib/cart.dart':"import 'package:aa/price.dart';",'a/lib/price.dart':'','b/pubspec.yaml':'name: bb\n','b/lib/price.dart':''}));assert.deepEqual([...g.adjacency.get('a/lib/cart.dart')],['a/lib/price.dart']);});
test('Dart package traversal and unknown files remain unresolved',()=>{const g=sourceGraph(repo({'pubspec.yaml':'name: app\n','lib/a.dart':"import 'package:app/../pubspec.yaml'; import '../../../outside.dart'; import 'missing.dart';"}));assert.equal(g.adjacency.get('lib/a.dart').size,0);assert.equal(g.issues.filter(i=>i.code==='unresolved').length,3);});
test('dynamic/unterminated Dart URIs do not become editable references',()=>{for(const text of ["import 'a${name}.dart';","import 'unterminated"]){const d=dartDirectives({content:text});assert.equal(d.directives.length,0);assert.ok(d.issues.length);}});
test('raw Dart URI strings are supported without evaluating interpolation',()=>{const d=dartDirectives({content:"import r'price.dart';"});assert.equal(d.directives[0].specifier,'price.dart');});
test('unclosed nested comments and triple strings are explicit lexical limitations',()=>{assert.ok(sourceTokens('/* /* missing').issues.includes('unterminated_comment'));assert.equal(dartDirectives({content:`import '''a.dart''';`}).directives.length,0);});
test('cyclic dependency closure terminates and is deterministic',()=>{const g=sourceGraph(repo({'pubspec.yaml':'name: app\n','lib/a.dart':"import 'b.dart';",'lib/b.dart':"import 'a.dart';"}));assert.deepEqual(dependencyClosure(g,['lib/a.dart']),['lib/a.dart','lib/b.dart']);});
test('Python relative imports include local modules and mark subset coverage',()=>{const g=sourceGraph(repo({'pyproject.toml':'[project]','app/cart.py':'from .price import amount\n','app/price.py':'amount=4'}));assert.ok(g.adjacency.get('app/cart.py').has('app/price.py'));assert.ok(g.issues.some(i=>i.code==='python_static_import_subset'));});
test('Python imports in docstrings and comments do not become graph edges',()=>{const g=sourceGraph(repo({'a.py':'"""\nimport hidden\n"""\n# import hidden\n','hidden.py':''}));assert.equal(g.adjacency.get('a.py').size,0);});
test('Go module imports include package siblings but exclude tests from production closure',()=>{const g=sourceGraph(repo({'go.mod':'module example.test/source\n','main.go':'package main\nimport "example.test/source/cart"\n','cart/cart.go':'package cart\n','cart/price.go':'package cart\n','cart/cart_test.go':'package cart\n'}));const c=dependencyClosure(g,['main.go']);assert.ok(c.includes('cart/cart.go'));assert.ok(c.includes('cart/price.go'));assert.ok(!c.includes('cart/cart_test.go'));});
test('Go import groups resolve each local module',()=>{const g=sourceGraph(repo({'go.mod':'module example.test/source\n','main.go':'package main\nimport (\n "example.test/source/a"\n "example.test/source/b"\n)\n','a/a.go':'package a','b/b.go':'package b'}));assert.equal(g.adjacency.get('main.go').size,2);});
test('C++ quoted headers use bounded local candidates, ignoring commented includes',()=>{const g=sourceGraph(repo({'src/a.cpp':'/*\n#include "fake.h"\n*/\n#include "a.h"\n','src/a.h':'','src/fake.h':''}));assert.deepEqual([...g.adjacency.get('src/a.cpp')],['src/a.h']);});
test('Swift target siblings are context candidates with explicit membership uncertainty',()=>{const g=sourceGraph(repo({'Package.swift':'// Swift manifest','Sources/Cart/Cart.swift':'import Foundation','Sources/Cart/Price.swift':'struct Price {}','Sources/Other/Other.swift':''}));assert.deepEqual([...g.adjacency.get('Sources/Cart/Cart.swift')],['Sources/Cart/Price.swift']);assert.ok(g.issues.some(i=>i.code==='native_target_membership_requires_toolchain'));});
test('React Native sibling platform variants are retained together',()=>{const g=sourceGraph(repo({'package.json':'{"dependencies":{"react-native":"1"}}','Button.ios.tsx':'','Button.android.tsx':'','Button.native.tsx':''}),{jsReferences:()=>[]});assert.equal(dependencyClosure(g,['Button.ios.tsx']).length,3);});
test('planner carries transitive Dart source, related tests, manifest and mobile checks',()=>{const s=flutter(),d=flutter('dest_app');const p=planFeature(s,d,'cart',{sourcePaths:['lib/cart.dart'],destinationPaths:['lib/cart.dart']});assert.ok(p.requiredSource.includes('lib/price.dart'));assert.ok(p.relatedTests.includes('test/cart_test.dart'));assert.ok(p.requiredSource.includes('pubspec.yaml'));assert.ok(p.platformChecks.includes('permissions and entitlements'));assert.ok(p.verification.some(c=>c.program==='flutter'&&c.args[0]==='test'));assert.ok(p.verification.every(c=>c.status==='not_run'&&c.requiresIsolation));});
test('explicit file scopes reject unread paths before model generation',()=>{const s=flutter(),d=flutter();assert.throws(()=>planFeature(s,d,'cart',{sourcePaths:['lib/unread.dart']}),/not in the inspected/);});
for(const value of [[],['../secret.dart'],['.env'],['x.dart','X.dart'],'lib/cart.dart',Array.from({length:21},(_,i)=>`x${i}.dart`)])test('invalid selector rejected: '+JSON.stringify(value),()=>assert.throws(()=>normalizeSelection(value)));
test('selection order canonicalizes for idempotency and leaves absence absent',()=>{assert.equal(normalizeSelection(undefined),undefined);assert.deepEqual(normalizeSelection(['b.dart','a.dart']),['a.dart','b.dart']);});
test('missing context is counted explicitly; work groups are not executed partial transfers',()=>{const s=flutter(),d=flutter();const p=planFeature(s,d,'cart',{sourcePaths:['lib/cart.dart'],destinationPaths:['lib/cart.dart']});const f=finalizePlan(p,{source:s.files.filter(f=>f.path==='lib/cart.dart'),destination:d.files});assert.equal(f.readiness,'needs_additional_context');assert.ok(f.contextCoverage.missingSource.includes('lib/price.dart'));assert.match(f.notice,/not a compiler result/);});
test('different implementation languages are a semantic-port warning, not claimed compatible',()=>{const p=planFeature(repo({'a.swift':'struct A {}'}),repo({'a.kt':'class A'}),'A',{sourcePaths:['a.swift'],destinationPaths:['a.kt']});assert.equal(p.crossLanguage,true);assert.ok(p.issues.some(i=>i.code==='cross_language_semantic_port_requires_review'));});
test('compact metadata excludes file bodies and has explicit output limits',()=>{const p=compactPlan(finalizePlan(planFeature(flutter(),flutter(),'cart',{sourcePaths:['lib/cart.dart'],destinationPaths:['lib/cart.dart']}),{source:flutter().files,destination:flutter().files}));assert.ok(Buffer.byteLength(JSON.stringify(p))<=24000);assert.ok(!JSON.stringify(p).includes('int total'));assert.equal(p.contextCoverage.complete,true);});
test('unrelated nested monorepo manifests are not pulled into the chosen app',()=>{const s=repo({'package.json':'{"dependencies":{"react":"1"}}','src/cart.js':'','apps/phone/pubspec.yaml':'name: phone','apps/phone/lib/main.dart':''});const p=planFeature(s,s,'cart',{sourcePaths:['src/cart.js'],destinationPaths:['src/cart.js'],jsReferences:()=>[]});assert.ok(!p.requiredSource.includes('apps/phone/pubspec.yaml'));});

test('pooled context includes a 60KB source plus a 40KB destination without raising the total cap',()=>{const s=repo({'lib/a.dart':'x'.repeat(60000)}),d=repo({'lib/b.dart':'y'.repeat(40000),'lib/extra.dart':'z'.repeat(20000)});const c=selectContext(s,d,{sourcePriority:['lib/a.dart'],destinationPriority:['lib/b.dart'],destinationFallback:['lib/extra.dart']});assert.equal(c.source.length,1);assert.equal(c.destination.length,1);assert.equal(c.source[0].content.length+c.destination[0].content.length,100000);});
test('context allocation keeps whole files and does not evict explicit priorities for fallbacks',()=>{const s=repo({'a.dart':'a'.repeat(60000),'b.dart':'b'.repeat(60000)}),d=repo({'c.dart':'c'.repeat(1000)});const c=selectContext(s,d,{sourcePriority:['a.dart'],destinationPriority:['c.dart'],sourceFallback:['b.dart']});assert.equal(c.source[0].path,'a.dart');assert.equal(c.source[0].content.length,60000);assert.ok(!c.source.some(f=>f.path==='b.dart'));});
