/** @file Executable static project/mobile intake tests; no SDK, provider, credentials or repository code execution. */
import test from 'node:test';
import assert from 'node:assert/strict';
import { eligiblePath } from '../lib/policy.mjs';
import { profileProject, readPubspec, languageForPath, componentsForPath, isProjectTest } from '../lib/project-profile.mjs';
/** Build a synthetic repository, never an authenticated customer snapshot. */
const repo = entries => ({ files:Object.entries(entries).map(([path,content])=>({path,content})), inventory:Object.keys(entries) });
for (const p of ['lib/cart.dart','ios/Cart.swift','android/Cart.kt','ios/Info.plist','android/app/src/main/AndroidManifest.xml','android/app/build.gradle.kts','ios/App.xcodeproj/project.pbxproj','App.csproj','src/mod.ex','proto/cart.proto','CMakeLists.txt']) {
  test('safe mobile/polyglot text admitted: '+p,()=>assert.equal(eligiblePath(p),true));
}
for (const p of ['.env','android/key.properties','android/local.properties','android/app/google-services.json','ios/GoogleService-Info.plist','ios/signing.p12','app.keystore','profile.mobileprovision','Pods/other/code.swift','.dart_tool/package_config.json','.gradle/cache/build.gradle','../lib/cart.dart','assets/avatar.png','model.safetensors']) {
  test('private, binary, generated or unsafe input excluded: '+p,()=>assert.equal(eligiblePath(p),false));
}
test('one central implementation language classifier includes Dart/Kotlin/Swift and JSX',()=>{for(const [p,l] of [['a.dart','dart'],['a.kt','kotlin'],['a.swift','swift'],['a.tsx','typescript'],['a.py','python'],['a.rs','rust']])assert.equal(languageForPath(p),l);assert.equal(languageForPath('a.png'),null);});
test('pubspec reads dependency names without confusing nested sdk keys',()=>{assert.deepEqual(readPubspec('name: source_app\ndependencies:\n  flutter:\n    sdk: flutter\n  http: ^1.0.0\ndev_dependencies:\n  flutter_test:\n    sdk: flutter\n'),{name:'source_app',dependencies:['flutter','http'],devDependencies:['flutter_test'],complete:true});});
test('complex YAML is not called fully parsed',()=>{for(const text of ['name: app\ndependencies: {http: any}','name: app\ndependency_overrides:\n  http: any','name: app\nworkspace:\n  - packages/a','name: app\ndependencies:\n  http: *shared'])assert.equal(readPubspec(text).complete,false);});
test('nested mobile projects are retained without flattening into the web root',()=>{const p=profileProject(repo({'package.json':'{"dependencies":{"next":"1"}}','apps/phone/pubspec.yaml':'name: phone\ndependencies:\n  flutter:\n    sdk: flutter\n','apps/phone/lib/main.dart':'void main() {}','apps/web/main.ts':'export {};'}));assert.deepEqual(p.components.map(c=>c.kind),['web','flutter']);assert.deepEqual(componentsForPath(p,'apps/phone/lib/main.dart').map(c=>c.kind),['flutter']);assert.ok(!p.components[0].languages.includes('dart'));});
test('React Native and Expo are not classified as ordinary web React',()=>{for(const kind of ['react-native','expo']){const p=profileProject(repo({'package.json':JSON.stringify({dependencies:{react:'1',[kind]:'1'}}),'src/Cart.ios.tsx':'export {};'}));assert.equal(p.components[0].kind,kind);assert.equal(p.components[0].mobile,true);}});
test('native Android, Apple and MAUI have manifest evidence, not runtime claims',()=>{const p=profileProject(repo({'android/app/build.gradle.kts':'plugins { id("com.android.application") }','ios/App.xcodeproj/project.pbxproj':'{}','maui/App.csproj':'<Project><UseMaui>true</UseMaui></Project>'}));assert.deepEqual(p.components.map(c=>c.kind),['android','apple-app','maui']);assert.ok(p.components.every(c=>c.verification==='not_run'));assert.equal(p.components[1].root,'ios');});
test('malformed package JSON is visible and never executed',()=>{const p=profileProject(repo({'package.json':'require("fs").rmSync("/")'}));assert.deepEqual(p.warnings,['malformed_manifest:package.json']);assert.deepEqual(p.components[0].dependencies,[]);});
test('non-object JSON cannot advertise fake dependencies',()=>{const p=profileProject(repo({'package.json':'["react-native"]'}));assert.equal(p.components[0].kind,'node');assert.equal(p.warnings.length,1);});
test('unread inventory manifests are recorded honestly',()=>{const p=profileProject({files:[],inventory:['pubspec.yaml']});assert.equal(p.components[0].evidenceRead,false);assert.equal(p.components[0].pubspecComplete,false);});
test('component inventory is deterministic and bounded',()=>{const r=repo(Object.fromEntries(Array.from({length:40},(_,i)=>[`p${i}/go.mod`,'module example.test/m'])));const a=profileProject(r),b=profileProject({...r,files:r.files.toReversed(),inventory:r.inventory.toReversed()});assert.deepEqual(a,b);assert.equal(a.components.length,32);assert.equal(a.omittedComponents,8);});
test('metadata without a manifest does not manufacture framework compatibility',()=>{const p=profileProject(repo({'Counter.swift':'struct Counter {}'}));assert.equal(p.components[0].kind,'source-only');assert.equal(p.components[0].evidenceRead,false);assert.deepEqual(p.languages,['swift']);});
test('mobile and native test naming is recognized as a discovery hint',()=>{for(const p of ['test/cart_test.dart','integration_test/cart_test.dart','src/androidTest/Cart.kt','CartTests.swift','cart_test.go','test_cart.py'])assert.equal(isProjectTest(p),true);assert.equal(isProjectTest('lib/cart.dart'),false);});
